### ISSUE TITLE
Queued device register access

### ISSUE THREAD

**Issue by aacuevas** [open-ephys/ONI#26]
I propose a new way to access device registers through an asynchronous use of the register and signal channels. It is intended to increase access speed to registers in some physical interfaces, such as the ft600 systems, although all of them could potentially benefit from its performance increase. This new form of access could coexist with the existing 1-register synchronous approach.

It would work like this:
1. Device register access setup would be performed on the Device Register Programming Interface as usual
2. Writing a `0x1` on `Trigger` would run the standard approach. Writing `0x2` (or whatever), however, will add the register access parameters (REG_ADDR, REG_VAL, RW) to an internal queue
3. A new register access (1-2) could be started without waiting for the existing register access to be completed: i.e.: Each register access is added to a queue and performed in order
4. When a queued register access is finished, the following newly defined `Signal` channel `PACKET_FLAG` values are sent: `CONFIGQWACK`, `CONFIGQWNACK`, `CONFIGQRACK` and `CONFIGQRACK`. These would all be atomic except `CONFIGQRACK` that would have the format `CONFIGQRACK register_value`. These must follow the same order as the queued requests.
5. The host would read these signals, reading as many ack/nacks as requests were send

A couple of details to maintain system coherence:
- If a normal register access (`Trigger = 0x1`) is requested while there are elements on the queue, the full queue will be aborted and a single newly defined `PACKET_FLAG`, `EINCOHERENT` (or something...),  will be returned. Explanation as to why: the signal channel is going to be used to return queued values. It cannot be used simultaneously to inform a blocking register access call of an ongoing non-blocking operation.
    - On a `EINCOHERENT` reception, the host should understand that the queue was aborted at a unspecified time and the last single access was not executed. This signal is game over because the queued access is in an undefined state. It should never be received with properly implemented API.
    - An API library (e.g.: `liboni`) should actually prohibit calling a single access before a full queue is executed. This behavior exists as an emergency fallback to avoid internal state corruption
- The queue might be implemented in a finite-sized FIFO. As such, if a request is sent that cannot be fit on the queue, the system will treat this case as a critical error, aborting the whole queue no matter its state, ignoring any further request and issuing a `CONFIGQOVERFLOW` flag over the signal channel.
    - This overflow mode can be exited, resetting the queue, by issuing a single-register request
    - Such a request when in overflow mode will return a nack, as stated previously, as the queue is still considered active, just "halted"
    - Same as before, an API library should be aware of the maximum elements that can fit a queue and never exceed them.
    
This feature could be implemented as a replacement of #7 or as another different capability, this needs to be discussed.
Likewise, hardware queue limitations could be reported by hardware as described in #6 . As discussed there, this could be either a core feature of a new spec version or an optional extension

**Comment by jonnew** [comment]
Note that steps 1-5 are all wrapped in a newly defined, blocking, API function call that takes pointers to arrays of addresses and values.

**Comment by aacuevas** [comment]
All the "failsafes" added on the second part of the issue are not going to be implemented, and will be undefined behavior.

**Comment by aacuevas** [comment]
Given that the API is gonna remain blocking, I am thinking about making this the only way to access registers. So instead of defining new signal `PACKET_FLAGS` we keep the old ones and just modify `CONFIGRACK` to include the register value.

API behavior will remain the same, just some under-the-hood tweaks will be necessary and it will simplify implementation by a great margin.

**Comment by jonnew** [comment]
I definitely like this. We also talked through the API and decided we should maintain the single access functions (`oni_read_reg` and `oni_write_reg`) but that they would likely be marked as inline in the API an simply specialize the more generic, and unified `oni_read_reg_multiple` and `oni_read_reg_multiple` functions (TODO: name these properly).

**Comment by cjsha** [comment]
`oni_read_reg_contiguous`?

**Comment by jonnew** [comment]
It looks like the standard method for doing this in e.g. Linux APIs and `glibc` is to use the plural version of the singular function:

``` c
oni_read_reg
oni_read_regs
oni_write_reg
oni_write_regs
```
![image](https://github.com/user-attachments/assets/b1288b8c-97e3-4de5-816c-269f7f1d8257)

![image](https://github.com/user-attachments/assets/2e887e76-c6ab-4b8f-b485-671b636fef97)

This is not very common though.
