### ISSUE TITLE
Swap global timestamp and device address in ONI frame

### ISSUE THREAD

**Issue by aacuevas** [open-ephys/ONI#30]
Currently an ONI frame, sent between the controller and the host, is defined as
```
uint64  Common_Timestamp
uint32  Device_Address
uint32  Sample_Size
var     Sample
```

I propose switching the timestamp and address 
```
uint32  Device_Address
uint64  Common_Timestamp
uint32  Sample_Size
var     Sample
```

This is specially useful for word boundary padding. Since a xx.xx.xx.255 address is already defined as invalid, we could just pad with 0xFF instead of 0xFF. This way, in either side of the communication, detecting a 0xFFFFFFFF where a device address should be, we can easily detect a non-frame. This has the potential to simplify boundary checking.

**Comment by jonnew** [comment]
That makes a lot of sense.

**Comment by aacuevas** [comment]
This introduces a small issue. Fore the write channel, we are not sending the global timestamp. Which is easier when it is first.
I still believe that having the order like this makes sense, but we need to decide how to tackle this. 
Possible approaches are:
1. Send the global timestamp, as all 0's. 
2. skip the global timestamp. 

When sending multiple samples at once, we only send the header once, so 1 would have little impact, while 2 makes the sending logic a bit more complex than just writing the whole fame buffer.

**Comment by jonnew** [comment]
One way to get around this is the following:

Read frames:
```
uint32  Device_Address
uint32  Sample_Size + 8 // Payload now includes Common_Timestamp as required first element
uint64  Common_Timestamp 
var     Sample
```

Write frames:
```
uint32  Device_Address
uint32  Sample_Size 
var     Sample
```

So now the header is just the `Device_Address` and `Sample_Size`. The `Common_Timestamp`'s size is included in the `Sample_Size` of  read frames and is a required element. Its simply not included in the write frames.
