### ISSUE TITLE
Define Configuration Register and Device Register

### ISSUE THREAD

**Issue by jonnew** [open-ephys/ONI#39]
In the glossary, we suggest the following definitions to be added:

Configuration Register
    Register accessed over the configuration channel.
 
Device Register
   Register governed by a Device and specified in its datasheet.

**Comment by aacuevas** [comment]
Should we add this to the glossary, or in the comm_channels.rst `Channel types` page, after the definition of a register channel? (definition which, by the way, requires tweaking as per our conversations regarding sizes)

**Comment by jonnew** [comment]
The conclusion here is a couple additions:

1. Add a term to glossary for "Register" - A 32-bit addressed value. The provide seealso link to Register Channel definition, which occurs on the Channel Types page.

2. Under the Register Channel definition on the Channel Types page, add an Note that indicates (a) that devices can hold registers and the the controller can hold registers, and these registers are as defined in 1., there mappings are different. The controller has a fixed set of registers that is defined on by the _address_global reference. The device registers are arranged as per the  _dev-register reference. 


Note: we are a bit unsure about the use of the term "Type" here:

https://github.com/open-ephys/ONI/blob/3cb24c032f5e4984d2a477721fdf567674b87588/source/hw-spec/devices/registers.rst?plain=1#L8

As, strickly speaking, regardless of their classification, these are still just registers from the spec's perspective.

**Comment by aacuevas** [comment]
Fixed in #64
