### ISSUE TITLE
Clarify the low-level nature of TRIGGER

### ISSUE THREAD

**Issue by jonnew** [open-ephys/ONI#52]
Per the discussion with Aaron, I think it would be good to have an admonition or something that explains TRIGGERS kind of weird behavior:

https://github.com/open-ephys/ONI/blob/b513c8fac62418e37448a2a140f74a0fda8b92fc/source/hw-spec/controller/register_interface.rst?plain=1#L35

When reading TRIGGER: you get a value that reflects the state of the register queue writing or reading state machine. 
When writing TRIGGER: you are asking the state machine to insert another element into the transaction queue. 

Therefore the value of trigger is not tied to some unique element like it would be in a file, but something more abstract.

**Comment by aacuevas** [comment]
Fixed in #59
